---
engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "ruleset.xml"
  csslint:
    enabled: true

prepare:
    fetch:
        - url: "https://raw.githubusercontent.com/silverstripe/silverstripe-link/master/tests/phpcs/ruleset.xml"
          path: "ruleset.xml"

ratings:
  paths:
  - "**.js"
  - "**.php"
  - "**.css"

exclude_paths:
