---
Name: linkfield
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\Link\LeftAndMainExtension

SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\Link\ModalControllerExtension

SilverStripe\Forms\TreeDropdownField:
  extensions:
    - SilverStripe\Link\TreeDropdownFieldExtension

SilverStripe\CMS\Forms\AnchorSelectorField:
  extensions:
    - SilverStripe\Link\TreeDropdownFieldExtension
