---
Name: linkfield
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\Link\Extensions\LeftAndMain

SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\Link\Extensions\ModalController

SilverStripe\Forms\TreeDropdownField:
  extensions:
    - SilverStripe\Link\Extensions\AjaxField

SilverStripe\CMS\Forms\AnchorSelectorField:
  extensions:
    - SilverStripe\Link\Extensions\AjaxField
